# Generated by Django 5.2.13 on 2026-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('GRADE_ASSIGNED', 'Grade Assigned'), ('SUBMISSION', 'New Submission'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=20),
        ),
    ]
