# Generated by Django 5.2.13 on 2026-05-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_core', '0002_portfolio_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated'), ('REDO', 'Redo Required')], default='DRAFT', max_length=20),
        ),
    ]
