# Generated by Django 5.2.13 on 2026-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_core', '0003_alter_portfolio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_redo_request',
            field=models.BooleanField(default=False),
        ),
    ]
