# Generated by Django 5.2.13 on 2026-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_core', '0004_assessment_is_redo_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
