# Generated by Django 5.2.13 on 2026-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_core', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='submission_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='submission_round',
            field=models.IntegerField(default=1),
        ),
    ]
