# Generated by Django 5.2.13 on 2026-06-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_element'),
        ('poe_core', '0007_evidence_submission_round_portfolio_submission_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='assessment_type',
            field=models.CharField(choices=[('PRACTICAL', 'Practical Assessments'), ('ORAL', 'Oral Assessments'), ('WRITTEN', 'Written Assessments'), ('ASSIGNMENT', 'Assignments'), ('SUPERVISED', 'Supervised Assessments')], default='PRACTICAL', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='academic.element'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='academic.unit'),
        ),
    ]
