# Generated by Django 5.2.13 on 2026-06-08 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_rubric_rubriccriterion'),
        ('poe_core', '0008_portfolio_assessment_type_portfolio_element_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='verification_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Audit'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Portfolio Created'), ('SUBMITTED', 'Portfolio Submitted'), ('EVALUATED', 'Portfolio Evaluated'), ('REDO_REQUESTED', 'Redo Requested'), ('EVIDENCE_ADDED', 'Evidence Uploaded'), ('EVIDENCE_DELETED', 'Evidence Deleted'), ('VERIFIED', 'CDACC Verified'), ('REJECTED', 'CDACC Rejected')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='poe_core.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_satisfied', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='poe_core.assessment')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.rubriccriterion')),
            ],
            options={
                'unique_together': {('assessment', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='PlagiarismFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='poe_core.evidence')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_flags', to='poe_core.evidence')),
            ],
            options={
                'unique_together': {('evidence', 'duplicate_of')},
            },
        ),
    ]
