# Generated by Django 5.2.13 on 2026-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_core', '0009_evidence_file_hash_portfolio_verification_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='evidence',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
