# Generated by Django 5.2.13 on 2026-07-02 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_core', '0010_alter_evidence_options_evidence_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
