# Generated by Django 5.2.13 on 2026-05-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_course_user_year_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('CDACC', 'CDACC')], default='STUDENT', max_length=20),
        ),
    ]
