# Generated by Django 5.2.13 on 2026-05-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_rename_department_school_remove_year_course_and_more'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='year',
            new_name='semester',
        ),
        migrations.AddField(
            model_name='user',
            name='intake',
            field=models.CharField(blank=True, choices=[('JANUARY', 'January Intake'), ('MAY', 'May Intake'), ('SEPTEMBER', 'September Intake')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.semester'),
        ),
    ]
