# Generated by Django 5.2.13 on 2026-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_year_user_intake_user_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(default='TEMP_ID', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
