# Generated by Django 5.2.13 on 2026-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
