# Generated by Django 5.2.13 on 2026-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_unit_code_alter_unit_unique_together'),
        ('users', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='academic.course'),
        ),
    ]
