# Generated by Django 5.2.13 on 2026-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_assigned_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cdacc_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
