# Generated by Django 5.2.13 on 2026-05-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0002_user_course_user_year_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='School',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='school',
        ),
        migrations.RenameModel(
            old_name='Year',
            new_name='Semester',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='year',
            new_name='semester',
        ),
        migrations.AlterField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academic.semester'),
        ),
    ]
