# Generated by Django 5.2.13 on 2026-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_rename_department_school_remove_year_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(5, 'Level 5 (Certificate)'), (6, 'Level 6 (Diploma)')], default=6),
        ),
    ]
