# Generated by Django 5.2.13 on 2026-05-04 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_course_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
