# Generated by Django 5.2.13 on 2026-05-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_unit_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('GRADE_I', 'Grade I'), ('GRADE_II', 'Grade II'), ('GRADE_III', 'Grade III'), ('LEVEL_3', 'Level 3'), ('LEVEL_4', 'Level 4'), ('LEVEL_5', 'Level 5'), ('LEVEL_6', 'Level 6'), ('HEADWAY', 'Headway')], default='LEVEL_6', max_length=20),
        ),
    ]
