# Generated by Django 5.2.13 on 2026-05-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academic.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='academic.semester'),
        ),
    ]
