# Generated by Django 5.2.13 on 2026-05-05 13:04

from django.db import migrations


def populate_course(apps, schema_editor):
    Unit = apps.get_model('academic', 'Unit')
    for unit in Unit.objects.all():
        if unit.semester and not unit.course:
            unit.course = unit.semester.course
            unit.save()

class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_unit_course_alter_unit_semester'),
    ]

    operations = [
        migrations.RunPython(populate_course),
    ]
