# Generated by Django 5.2.13 on 2026-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_populate_unit_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('code', 'course')},
        ),
    ]
