# Generated by Django 5.2.13 on 2026-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
