# Generated by Django 5.2.13 on 2026-06-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_unit_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('code', 'semester')},
        ),
    ]
