# Generated by Django 5.2.13 on 2026-06-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_unit_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake', models.CharField(choices=[('JANUARY', 'January Intake'), ('MAY', 'May Intake'), ('SEPTEMBER', 'September Intake')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.semester')),
            ],
            options={
                'unique_together': {('course', 'intake', 'semester')},
            },
        ),
    ]
