# Generated by Django 5.2.13 on 2026-06-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_examrepository_gradingsystem_graderange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='credit_hours',
            field=models.IntegerField(default=45),
        ),
    ]
