# Generated by Django 5.2.13 on 2026-07-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_unit_credit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmarkcomponent',
            name='formula',
            field=models.CharField(blank=True, choices=[('SUM', 'Sum'), ('AVERAGE', 'Average'), ('BEST_OF', 'Best Of')], default='SUM', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unitmarkcomponent',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitmarkcomponent',
            name='group_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
