# Generated by Django 5.2.13 on 2026-07-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_unitmarkcomponent_formula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('class_name', models.CharField(default='Computer Studies', max_length=255)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_reg_no', models.CharField(max_length=100)),
                ('has_started', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('has_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academic.onlineexam')),
            ],
            options={
                'unique_together': {('exam', 'student_reg_no')},
            },
        ),
    ]
