# Generated by Django 5.2.13 on 2026-07-15 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_onlineexam_onlineexamattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='HEADWAY COLLEGE OF PROFESSIONAL STUDIES', max_length=255)),
                ('college_motto', models.CharField(default='Learning for Global Relevance', max_length=255)),
                ('title', models.CharField(default='Certificate of Competence', max_length=255)),
                ('sub_title', models.CharField(default='This is to Certify that', max_length=255)),
                ('intro_text', models.TextField(default='Has successfully completed and passed all the prescribed modules per requirement and the award of')),
                ('modules_heading', models.CharField(default='Modules Covered', max_length=255)),
                ('footnote_text', models.TextField(default='This Certificate was issued without any erasure or alterations whatsoever and Invalid without an Official Seal')),
                ('director_title', models.CharField(default='Director of Studies', max_length=255)),
                ('principal_title', models.CharField(default='Principal', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_ref_no', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=255)),
                ('award_title', models.CharField(default='Proficiency Certificate in Computer Applications', max_length=255)),
                ('modules_covered', models.JSONField(default=list)),
                ('date_earned', models.CharField(max_length=100)),
                ('print_date', models.CharField(max_length=100)),
                ('qr_code_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
