# Generated by Django 5.2.13 on 2026-07-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_certificatetemplate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='award_title_font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='college_name_font_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='logo_size',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='modules_font_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='primary_color',
            field=models.CharField(default='#0000FE', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='secondary_color',
            field=models.CharField(default='#dc2626', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='spacing_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='student_name_font_size',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_font_size',
            field=models.IntegerField(default=24),
        ),
    ]
